(MAINT) Update CONTRIBUTING.md for new Feature Request policy
puppetlabs/pdk pull request #1033
Opened 2021-03-24 17:09 UTC by sanfrancrisko

Given the introduction of [Discussions](https://github.com/puppetlabs/pdk/discussions),
we want ensure that Feature Requests are raised via the Discussions
route, rather than directly as an Issue Type.

See also: https://github.com/puppetlabs/pdk/pull/1032

2021-03-24 17:17 UTC, jpogran requested changes

2021-03-24 17:17 UTC, jpogran commented on CONTRIBUTING.md
> +PRs to resolve issues discovered are greatly appreciated - please post questions to [puppet-users@groups.google.com](https://groups.google.com/forum/#!forum/puppet-users) or start a Discussion [here]
```suggestion
PRs to resolve issues discovered are greatly appreciated - please start a Discussion [here](https://github.com/puppetlabs/pdk/discussions) or post a question to [puppet-users@groups.google.com](https://groups.google.com/forum/#!forum/puppet-users).
```

2021-03-24 17:57 UTC, da-ar reviewed
@sanfrancrisko  there are a number for single line returns in the raw file, however when the markdown renders these are ignored. I'm not sure if that is intended? GitHub markdown requires a double space to get the carriage return.

I use the [markdown lint VS Code addon](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) which I find useful.

2021-03-24 23:31 UTC, sanfrancrisko commented
> @sanfrancrisko there are a number for single line returns in the raw file, however when the markdown renders these are ignored. I'm not sure if that is intended? GitHub markdown requires a double space to get the carriage return.
> 
> I use the [markdown lint VS Code addon](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) which I find useful.

Still getting used to VSCode 😆

2021-03-25 00:09 UTC, da-ar commented
> ...but, actually, yes - they were intended. I'm following [semantic line break](https://sembr.org/) convention. Say I had a paragraph and you wanted to suggest a change to a sentence, it means it can be suggested without the whole paragraph being highlighted in a code review.

That makes a lot of sense and is a new one on me, thanks.

2021-03-25 10:16 UTC, merged